name: goatcounter

services:
  goatcounter:
    image: arp242/goatcounter:latest
    container_name: goatcounter
    restart: unless-stopped
    ports:
      - '127.0.0.1:18087:8080'
    volumes:
      - goatcounter-data:/home/goatcounter/goatcounter-data

volumes:
  goatcounter-data:
